### ISSUE TITLE
Отклонения при расчёте процентов в методе yearChange класса CreditAccount при малых значениях баланса

### ISSUE THREAD

**Issue by vOrzee** [vOrzee/javaqa-team-diplom-2#14]
# Описание

Процентный расчет приводит к невалидному результату из-за целочисленного деления при определении суммы процентов.

# Локация дефекта

В текущей реализации некорректные данные получаем здесь:
https://github.com/vOrzee/javaqa-team-diplom-2/blob/d6e9201647dbc26451f5bfe861030948e678b35d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L84

# Шаги воспроизведения

1. Открыть в проекте [тест shouldTestYearChange](https://github.com/vOrzee/javaqa-team-diplom-2/blob/d6e9201647dbc26451f5bfe861030948e678b35d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L70-L87) в IDE
1. Провести операцию расчёта процентов с помощью вызова метода `yearChange`
1. Посмотреть на вывод в консоли для случая с начальным балансом -99 и процентной ставкой 15%.

*Ожидаемый результат:* сумма процентов равна -14
*Фактический результат:* сумма процентов равна 0

# Скриншот
<img width="1206" alt="Снимок экрана 2024-10-15 в 03 52 06" src="https://github.com/user-attachments/assets/c702117d-e5fa-47a3-b737-87d60f97c1a4">

# Окружение

- **Операционная система:** macOS Sequoia 15.0.1 (24A348)
- **IDE:** GIGA IDE 2024.1.1 (Community Edition)
- **Java:** Eclipse Temurin 11.0.24 - aarch64

**Comment by NikitaLeon** [comment]
# Окружение
* **Операционная система:** Windows 10 Version 22H2
* **IDEA:** Intellij IDEA Community Edition 2023.3.4
* **Java:** Open JDK 11
